### ISSUE TITLE
Can't build after cocoapods install using use_frameworks! option  (Include of non-modular header inside framework module 'ogg')

### ISSUE THREAD

**Issue by c7l8** [brion/OGVKit-Specs#2]
Using:
- XCode Version: 7.3
- CocoaPods Version: 0.39.0

---

**Steps to reproduce the error:**

1) Create a Swift based project with the following Podfile: 

```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brion/OGVKit-Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'OGVKit-Test-iOS' do
  pod "OGVKit", '~> 0.5pre'
end
```

2) Install the pod

3) Compile.

Xcode reports this compilation errors:

<img width="260" alt="screen shot 2016-03-28 at 4 47 35 pm" src="https://cloud.githubusercontent.com/assets/531295/14093168/24625688-f509-11e5-904c-08af319365d2.png">

**Comment by bvibber** [comment]
Poking it to see what's going on... Ugh, not sure how this worked before now that I'm looking at it....? o_O

Note it's specifically crapping out on #  include <inttypes.h> ... which you'd think would work since it's a standard C header? Heh.

**Comment by bvibber** [comment]
Ok, I've got the module map mostly fixed but it's also necessary to remove the inttypes.h include. If I can't find a workaround I'll add a patch to the package setup.

**Comment by bvibber** [comment]
Here's libgit2 encountering the same problem with inttypes.h: https://github.com/libgit2/libgit2/commit/1ddada422caf8e72ba97dca2568d2bf879fed5f2

Looks like just patching out the include for now should do the job.

**Comment by bvibber** [comment]
Whoops wrong link: https://github.com/libgit2/libgit2/commit/1ddada422caf8e72ba97dca2568d2bf879fed5f2

**Comment by bvibber** [comment]
Ok I think I have this working as of 7e27157996 -- the example is now building for me once I nuke the Pods & Podfile.lock and re-run pod install.

There's still some warnings which I'll have to track down further, but those look less explode-y.

@c7l8 can you confirm it work with your Swift project now?

**Comment by c7l8** [comment]
> Poking it to see what's going on... Ugh, not sure how this worked before now that I'm looking at it....? o_O

Apple Compiler (Cocoapods?) magic 😅

> @c7l8 can you confirm it work with your Swift project now?

I just checked and Its working nice :D

Thank you for your quick response.

**Comment by c7l8** [comment]
Although looks like the subspecs still have issues.

With `pod "OGVKit/Ogg", '~> 0.5pre'`

<img width="256" alt="screen shot 2016-03-28 at 7 34 03 pm" src="https://cloud.githubusercontent.com/assets/531295/14095360/b6bbe07c-f51c-11e5-8cb9-ea4e9d96332e.png">

**Comment by bvibber** [comment]
I'll open a fresh issue for the subspecs over on the OGVKit core repo. Thanks for testing!
