### ISSUE TITLE
Update OGVKit dependencies git source url

### ISSUE THREAD

**Issue by khaojam** [brion/OGVKit-Specs#6]
Hi,

1. The existing https://git.xiph.org/xiph/liboggz.git no longer available, and it has been migrated to https://gitlab.xiph.org/xiph/liboggz.git
2. http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz not available as well

**Comment by bvibber** [comment]
To warn, I'm no longer maintaining this project and will archive the repos soon once I update the readme files.

I recommend using MobileVLCKit or GStreamer instead, both of which support a larger number of formats and have more mature playback engines.

**Comment by khaojam** [comment]
Thanks @brion for the replied and suggestions.
