### ISSUE TITLE
Error installing liboggz

### ISSUE THREAD

**Issue by YankoSoulisimo** [brion/OGVKit-Specs#7]
[!] Error installing liboggz
[!] /usr/bin/git clone https://git.xiph.org/liboggz.git /var/folders/lh/8rtrvwm54kl3p0p_r66zqx5r0000gp/T/d20200724-7513-htz0l2 --template=

Cloning into '/var/folders/lh/8rtrvwm54kl3p0p_r66zqx5r0000gp/T/d20200724-7513-htz0l2'...
fatal: unable to access 'https://git.xiph.org/liboggz.git/': Failed to connect to git.xiph.org port 443: Connection refused

It turned out that https://git.xiph.org/liboggz.git/ is now here --> https://gitlab.xiph.org/xiph/liboggz

Made a fork and replaced source with https://gitlab.xiph.org/xiph/liboggz, works fine.

**Comment by bvibber** [comment]
OGVKit is no longer under development. Thanks for your interest! Feel free to use the code, but you'll be responsible for any upkeep and maintenance.
